language: go
go: 1.9.x

branches:
    only:
        - master
        - develop
jobs:
    include:
        - stage: lint
          script:
              - ./ci/validate-gofmt.sh
              - go get -u github.com/golang/lint/golint
              - ./ci/validate-lint.sh
        - stage: test
          script:
              - sudo apt-get install -y build-essential
              - make test
